### ISSUE TITLE
🐛 VS Code extension can't run in vscode dev container

### ISSUE THREAD

**Issue by zfben** [biomejs/biome-vscode#22]
### Environment information

```block
We use devcontainer for development, and want to replace eslint with biome.
```

### What happened?

1. Try to install biome extension
2. Display error message: `The 'biomejs.biome' extension is not available in Visual Studio Code for Alpine Linux 64 bit.`

### Expected result

It works in dev container.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
Hey @zfben,

Thanks for opening this issue.

Since [v2.0.0](https://github.com/biomejs/biome-vscode/releases/tag/v2.0.0), we no longer build platform-specific distributions of the extension, so you should be able to load the extension inside the container.

However, to be able to run Biome on Alpine, you'll most likely have to wait for Biome 1.4 (shipping early next week), which will introduce Alpine-compatible binaries.

I'll close the issue for now, but feel free to create a new one if you're still encountering this issue in the future.

**Comment by ematipico** [comment]
I suppose this is an enhancement that now we can land now, since we're able to ship a binary for Alpine.
