### ISSUE TITLE
Add `configPath` option 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome-vscode#28]
This option will allow the extension to resolve the configuration from a different path, as opposed to the default configuration resolution.

This option will pass `--config-path` to the CLI, so it will behave the same.

**Comment by nhedger** [comment]
Addressing this issue might be dependent on #27.

**Comment by nhedger** [comment]
If the `biome.configPath` option is not specified, should it:

1. Pass `<workspace-root>/biome.json` to the CLI as the `--config-path` option
	- How does the CLI handle the absence of this file?
3. Not pass the `--config-path` option at all

**Comment by ematipico** [comment]
We should not pass the option at all. The `--config-path` option changes slightly how the resolutions work (which I should document).

When we pass `--config-path`, Biome **doesn't** do any resolution by looking at parent directories.

**Comment by FedericoBiccheddu** [comment]
The related MR is closed saying there will be another path to implementation, but issue marked as completed.

Just to be sure, is still planned or implemented?

**Comment by panukettu** [comment]
I hoped this or similar capability existed - until I realized to just create a fallback biome config higher up in the filesystem. 

Before this, it required a lot of willpower to keep this extension when a bunch of linter errors appear in a project that does not want a biome config. (magnified by the fact that biome seems to require ignore-comments on each diagnostic)

imo for general usage its better (less context switchy) if biome defaults could be overridden in vscode settings - instead of a separate config file.

**Comment by nfm** [comment]
@nhedger would it be possible to reopen this issue given the approach in #33 didn't pan out?

In case it's helpful context, my use-case for this is that I have a monorepo with standalone packages in subdirectories, some of which need biome and others of which don't. Unless I put `biome.json` in the top-level directory of the repo, the VSCode extension can't find it and uses the biome default settings.

**Comment by nfm** [comment]
Did some more digging - links to upstream issues in biome LSP itself for those interested:

- https://github.com/biomejs/biome/issues/1573
- https://github.com/biomejs/biome/issues/2228

**Comment by nhedger** [comment]
The pre-release supports this using explicitly defined projects.

Docs: https://deploy-preview-974--biomejs.netlify.app/reference/vscode/#defining-projects
Config reference: https://deploy-preview-974--biomejs.netlify.app/reference/vscode/#biomeprojects

**Comment by skipjack** [comment]
@nhedger tried these two approaches with no luck, restarted the biome server after each edit. You can see in the second screenshot that VS Code isn't recognizing it. I'm probably missing something obvious about how these settings work (note that I'm in Cursor rather than VS Code proper but I don't think that should matter in regards to this)...

<img width="840" alt="Image" src="https://github.com/user-attachments/assets/de2cc422-0e50-423b-b48f-9d0b29cb5542" />

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/46398f7f-cedb-4521-b820-367709f2599b" />
