### ISSUE TITLE
🐛 Biome show lint errors in projects with not biome setup 

### ISSUE THREAD

**Issue by nathanredblur** [biomejs/biome-vscode#301]
### VS Code version

1.92.0

### Extension version

2.3.0

### Biome version

1.8.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

I installed biome vscode extension to see the lint errors in a new project with biome rules.
but now, I see biome errors in other projects that not use biome setup.
for example, I create a new project with t3 and I see biome errors and I shouldn't create a biome config file to disable that error.

![CleanShot 2024-08-11 at 19 12 12](https://github.com/user-attachments/assets/10043cdb-649d-4982-a96f-8c8ad49e8b89)

![CleanShot 2024-08-11 at 19 12 27](https://github.com/user-attachments/assets/e2c772f0-73e3-4a1c-bd7d-bb69f26daa6d)

### Steps to reproduce

1. install biome vscode extension
2. create a new project that not use biome and has ESLint rules like `pnpm create t3-app@latest`
3. notice how you see biome lint errors.

### Expected behavior

If not exist a `biome.json` file, not show lint errors like biome[lint/style/useImportType](https://biomejs.dev/linter/rules/use-import-type)

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by dyc3** [comment]
As far as I know, this is intentional. Biome generally prefers use cases that require the least amount of configuration for a better user experience. Biome assumes a "default" configuration when none is provided, and will emit diagnostics as such. 

As a workaround in vscode, you can disable the extension per workspace.

**Comment by ematipico** [comment]
This will be fixed in V3

**Comment by eps1lon** [comment]
@ematipico Is v3 the version you get when you switch to using the release candidate? I switched to using the release candidate yet the extension is still linting repositories that do not use Biome. This is a problem since I have a mixed workspace consisting of repositories using Biome and some that don't. Forcing me to choose an all or nothing approach for my workspace hurts migrating efforts.

**Comment by nhedger** [comment]
> @ematipico Is v3 the version you get when you switch to using the release candidate? I switched to using the release candidate yet the extension is still linting repositories that do not use Biome. This is a problem since I have a mixed workspace consisting of repositories using Biome and some that don't. Forcing me to choose an all or nothing approach for my workspace hurts migrating efforts.

V3 is a work in progress and has not yet been released as a nightly version. Can't promise anything but I expect to ship it sometime at the end of August/ early September.
