### ISSUE TITLE
Missing Biome warning should be optional

### ISSUE THREAD

**Issue by GRA0007** [biomejs/biome-vscode#74]
I work with several projects and some of them do not (yet!) use Biome. Currently the extension shows this warning every time a project without Biome is loaded:

```
Could not find Biome in your dependencies. Either add the @biomejs/biome package to your dependencies, or download the Biome binary.
```

I propose that a `biome.warnIfDependencyMissing` setting be added that allows disabling this warning, and a "Don't remind me again" option be added to the warning that sets this setting to `false`.

I'd be happy to work on this if it's something others want 👌

**Comment by nhedger** [comment]
Hey @GRA0007,

Thanks for opening this issue.

We're working on an improved detection mechanism and new options that should solve this issue. I will keep you informed.

**Comment by tylerlaprade** [comment]
I came here to report a similar issue with this warning, but triggered in a different context. Since it's similar enough, I'll put it here rather than creating a new issue.

I have Biome specified in my `package.json`'s `devDependencies` (not `dependencies`, since it's not needed for the actual app`). Every time I reload the window, I see this warning pop up even though I have Biome in my dependencies.

**Comment by nhedger** [comment]
This will no longer be an issue in v3. Closing since we've started publishing the nightly.

**Comment by printfn** [comment]
Is there a plan for when v3 with this fix might be released?

**Comment by dyc3** [comment]
We don't really have ETAs for when stuff will get released. We're still kinda feeling it out and gathering bug reports for v3. If you want this right now, you can switch over to the prerelease in vscode by clicking the "switch to prerelease" button.
